# -*- coding: utf-8 -*-
"""Conversor Imagem em PDF

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jnYXGLP9VdZgCAx48wiiQ2Aya_o93CC9
"""

pip install img2pdf



import img2pdf
from PIL import Image
import os

arquivo = ('arquivo a ser convertido aqui.extensão')
arquivo_pdf = ('caminhodoarquivofinal.pdf')

image = Image.open(arquivo)

pdf_bytes = img2pdf.convert(image.filename)

file = open(arquivo_pdf, "wb")

file.write(pdf_bytes)

image.close()

file.close()